<a href="https://colab.research.google.com/github/kuroooooooooo/smart1/blob/main/ch01_02_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
nums1 = np.array(range(1, 11))
nums2 = np.array([10, 20, 30])

nums1, type(nums1), nums2

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]),
 numpy.ndarray,
 array([10, 20, 30]))

In [7]:
#인덱싱과 슬라이싱

nums1[5],nums1[-1],nums1[2:9]

(6, 10, array([3, 4, 5, 6, 7, 8, 9]))

## 난수발생 ひぃぃ

In [18]:
# 0 ~ 1 사이의 실수 1개 생성 
np.random.seed(2000)

x = np.random.random(10)
x, type(x)

(array([0.57051729, 0.56452876, 0.48844183, 0.33647775, 0.37586818,
        0.53203587, 0.06810629, 0.58452906, 0.23789776, 0.16075658]),
 numpy.ndarray)

In [20]:
rnds = np.random.random((3,3))
rnds

array([[0.86765533, 0.26187438, 0.49939512],
       [0.4285644 , 0.53000389, 0.57394682],
       [0.39185565, 0.07951412, 0.86728101]])

In [31]:
# 0~9 사이의 정수 
x1 = np.random.randint(10, size=6)
x2 = np.random.randint(10, size=(3,4))
x3 = np.random.randint(10, size=(3,4,5))
x4 = np.random.randint(10, size=(3,4,5,6))
x1
x2
x3
x4

array([[[[6, 7, 4, 7, 6, 8],
         [1, 0, 8, 9, 6, 3],
         [4, 4, 8, 7, 6, 5],
         [3, 0, 5, 8, 3, 7],
         [8, 7, 5, 9, 8, 5]],

        [[3, 2, 8, 0, 2, 0],
         [9, 3, 5, 5, 5, 6],
         [6, 1, 0, 5, 9, 1],
         [6, 7, 9, 5, 8, 4],
         [9, 6, 5, 5, 9, 3]],

        [[0, 2, 4, 1, 7, 6],
         [2, 9, 3, 3, 0, 6],
         [9, 0, 9, 9, 6, 4],
         [0, 6, 1, 5, 6, 5],
         [9, 1, 5, 3, 8, 9]],

        [[0, 1, 2, 3, 9, 4],
         [4, 6, 7, 8, 1, 2],
         [9, 3, 0, 6, 0, 1],
         [3, 1, 3, 3, 7, 5],
         [1, 3, 6, 6, 4, 2]]],


       [[[5, 3, 2, 7, 8, 1],
         [8, 9, 1, 5, 2, 0],
         [2, 9, 2, 2, 6, 6],
         [0, 9, 9, 5, 4, 4],
         [9, 4, 4, 7, 2, 8]],

        [[9, 5, 6, 0, 7, 9],
         [3, 4, 7, 3, 9, 5],
         [7, 4, 8, 8, 0, 7],
         [4, 6, 1, 4, 3, 0],
         [8, 2, 5, 5, 9, 2]],

        [[7, 3, 7, 7, 2, 5],
         [2, 0, 0, 4, 0, 0],
         [0, 0, 2, 9, 2, 0],
         [6, 0, 4, 3, 8, 6],


In [28]:
# 균등 분포
r1 = np.random.rand(3,2)
r1

array([[0.95579903, 0.6628237 ],
       [0.445998  , 0.75670717],
       [0.68923742, 0.14081001]])

In [32]:
# 이항분포 
b1 = np.random.binomial(10, 0.1, size=(2,5))
b1

array([[1, 1, 1, 0, 1],
       [0, 0, 1, 2, 1]])

In [35]:
#정규분포
n1 = np.random.normal(0, 1, size=(3,4))
n1

array([[-0.34945911,  0.06120519,  0.84378041, -0.69561433],
       [-0.73092701,  0.95427475,  0.38392292, -0.53320724],
       [ 0.114937  , -0.40334977, -0.31890727,  0.61725555]])

In [37]:
# 표준 정규 분포 
dn = np.random.randn(10)
dn

array([-1.03480125, -1.74587845, -1.81870981, -0.98759676, -1.00855455,
       -0.84543998,  1.71058426, -1.58501287,  1.14076338,  1.32049329])

## 불 마스킹과 팬시 인덱싱 

In [38]:
age = np.random.randint(1, 100, size=10)
age

array([98,  1, 66, 75,  9, 54, 45, 24, 67, 84])

In [39]:
#나이에서 20 ~ 60 세 데이터만 추출

age_mask = (age >=20) & (age <=60)
age_mask

array([False, False, False, False, False,  True,  True,  True, False,
       False])

In [40]:
age2 = age[age_mask]
age2

array([54, 45, 24])

In [43]:
age[[1,3,-2]]

array([ 1, 75, 67])

In [44]:
n1.shape

(3, 4)

In [45]:
#reshape
x = np.arange(12)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [52]:
x.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [54]:
n1 = range(1, 11)
n2 = range(11, 21)


TypeError: ignored

In [55]:
n = []
for i, v in enumerate(n1):
  n.append(n1[i] + n2[i])
print(n)

[12, 14, 16, 18, 20, 22, 24, 26, 28, 30]


In [57]:
# numpy 배열은 기본 요소끼리의 연산을 지원
n1 = np.array(n1)
n2 = np.array(n2)
n3 = n1 + n2
n3
# 이런 배열끼리의 연산을 "브로드 캐스팅"이라고 한다. 

array([12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [62]:
n3 = (n2 *2)/2
n3

array([11., 12., 13., 14., 15., 16., 17., 18., 19., 20.])

In [67]:
# 유니버셜 함수 - 브로드캐스팅의 함수 버전 
np.add(n1, 3)

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [69]:
np.random.seed(0)
a = np.random.randint(1, 10, 10)
b = np.random.randint(1, 10, 10)
a , b

(array([6, 1, 4, 4, 8, 4, 6, 3, 5, 8]), array([7, 9, 9, 2, 7, 8, 8, 9, 2, 6]))

In [71]:
mask = np.greater(a,b)
mask

a[mask]

array([4, 8, 5, 8])